### ISSUE TITLE
Error suspected in step03 in running kmeans.py locally

### ISSUE THREAD

**Issue by adamdingliang** [jyyulab/MICA#1]
nodecn112 rprod MICA$ ./tests/test_PBMC_mini_no_install_local.sh 
[INFO] --> [MICA] Finished.

OpenBLAS blas_thread_init: pthread_create: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1024 current, 1033162 max

OSError: ``./test_data/outputs/test_no_install_local/MICA_test_no_install_local_MDS_3/MICA_out/.tmp`` does not exist
Traceback (most recent call last):
  File "/home/lding/Git/MICA/MICA/kmeans.py", line 7, in <module>
    utils.kmeans(sys.argv[1], sys.argv[2], int(sys.argv[3]), int(sys.argv[4]), sys.argv[5], sys.argv[6])
  File "/research/rgs01/home/clusterHome/lding/Git/MICA/MICA/utils.py", line 277, in kmeans
    hdf = pd.HDFStore(in_mat_file)
  File "/hpcf/apps/python/install/3.6.1/lib/python3.6/site-packages/pandas/io/pytables.py", line 467, in __init__
    self.open(mode=mode, **kwargs)
  File "/hpcf/apps/python/install/3.6.1/lib/python3.6/site-packages/pandas/io/pytables.py", line 580, in open
    self._handle = tables.open_file(self._path, self._mode, **kwargs)
  File "/hpcf/apps/python/install/3.6.1/lib/python3.6/site-packages/tables/file.py", line 320, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "/hpcf/apps/python/install/3.6.1/lib/python3.6/site-packages/tables/file.py", line 784, in __init__
    self._g_new(filename, mode, **params)
  File "tables/hdf5extension.pyx", line 371, in tables.hdf5extension.File._g_new
  File "/hpcf/apps/python/install/3.6.1/lib/python3.6/site-packages/tables/utils.py", line 185, in check_file_access
    check_file_access(filename, 'w')
  File "/hpcf/apps/python/install/3.6.1/lib/python3.6/site-packages/tables/utils.py", line 175, in check_file_access
    raise IOError("``%s`` does not exist" % (parentname,))

**Comment by pNKz7mD0jz89KSShpK04tgEKc6OtEInKODtyxWB** [comment]
should be fixed in newer version
