### ISSUE TITLE
unable to lock file

### ISSUE THREAD

**Issue by adamdingliang** [jyyulab/MICA#6]
Traceback (most recent call last):
  File "/research/rgs01/home/clusterHome/lding/.conda/envs/py361_test/lib/python3.6/site-packages/MICA-0.1.0-py3.6.egg/MICA/bin/clustering.py", line 87, in <module>
    main()
  File "/research/rgs01/home/clusterHome/lding/.conda/envs/py361_test/lib/python3.6/site-packages/MICA-0.1.0-py3.6.egg/MICA/bin/clustering.py", line 42, in main
    args.umap_min_dist, args.tsne_perplexity, args.plot_dim, args.n_thread, args.dim_km)
  File "/research/rgs01/home/clusterHome/lding/.conda/envs/py361_test/lib/python3.6/site-packages/MICA-0.1.0-py3.6.egg/MICA/bin/clustering.py", line 69, in clustering
    common_name=out_name, dims=dim_km, num_processes=n_processes)
  File "/research/rgs01/home/clusterHome/lding/.conda/envs/py361_test/lib/python3.6/site-packages/MICA-0.1.0-py3.6.egg/MICA/bin/clustering.py", line 47, in km_multiprocess
    hdf = pd.HDFStore(mi_file)
  File "/home/lding/.conda/envs/py361_test/lib/python3.6/site-packages/pandas/io/pytables.py", line 505, in __init__
    self.open(mode=mode, **kwargs)
  File "/home/lding/.conda/envs/py361_test/lib/python3.6/site-packages/pandas/io/pytables.py", line 627, in open
    self._handle = tables.open_file(self._path, self._mode, **kwargs)
  File "/home/lding/.conda/envs/py361_test/lib/python3.6/site-packages/tables-3.5.2-py3.6-linux-x86_64.egg/tables/file.py", line 320, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "/home/lding/.conda/envs/py361_test/lib/python3.6/site-packages/tables-3.5.2-py3.6-linux-x86_64.egg/tables/file.py", line 784, in __init__
    self._g_new(filename, mode, **params)
  File "tables/hdf5extension.pyx", line 492, in tables.hdf5extension.File._g_new
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "H5F.c", line 511, in H5Fopen
    unable to open file
  File "H5Fint.c", line 1519, in H5F_open
    unable to lock the file
  File "H5FD.c", line 1650, in H5FD_lock
    driver lock request failed
  File "H5FDsec2.c", line 941, in H5FD_sec2_lock
    unable to lock file, errno = 11, error message = 'Resource temporarily unavailable'

End of HDF5 error back trace

Unable to open/create file '/research/rgs01/scratch_lsf/lsftmpdir/nodecn257/93666268.tmpdir/tmp44ejg7gf/stg738b285c-7c95-47f0-b268-f59ca310f275/PBMC12k_reduced.h5'
Traceback (most recent call last):
  File "/research/rgs01/home/clusterHome/lding/.conda/envs/py361_test/lib/python3.6/site-packages/MICA-0.1.0-py3.6.egg/MICA/bin/clustering.py", line 87, in <module>
    main()
  File "/research/rgs01/home/clusterHome/lding/.conda/envs/py361_test/lib/python3.6/site-packages/MICA-0.1.0-py3.6.egg/MICA/bin/clustering.py", line 42, in main
    args.umap_min_dist, args.tsne_perplexity, args.plot_dim, args.n_thread, args.dim_km)
  File "/research/rgs01/home/clusterHome/lding/.conda/envs/py361_test/lib/python3.6/site-packages/MICA-0.1.0-py3.6.egg/MICA/bin/clustering.py", line 69, in clustering
    common_name=out_name, dims=dim_km, num_processes=n_processes)
  File "/research/rgs01/home/clusterHome/lding/.conda/envs/py361_test/lib/python3.6/site-packages/MICA-0.1.0-py3.6.egg/MICA/bin/clustering.py", line 47, in km_multiprocess
    hdf = pd.HDFStore(mi_file)
  File "/home/lding/.conda/envs/py361_test/lib/python3.6/site-packages/pandas/io/pytables.py", line 505, in __init__
    self.open(mode=mode, **kwargs)
  File "/home/lding/.conda/envs/py361_test/lib/python3.6/site-packages/pandas/io/pytables.py", line 627, in open
    self._handle = tables.open_file(self._path, self._mode, **kwargs)
  File "/home/lding/.conda/envs/py361_test/lib/python3.6/site-packages/tables-3.5.2-py3.6-linux-x86_64.egg/tables/file.py", line 320, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "/home/lding/.conda/envs/py361_test/lib/python3.6/site-packages/tables-3.5.2-py3.6-linux-x86_64.egg/tables/file.py", line 784, in __init__
    self._g_new(filename, mode, **params)
  File "tables/hdf5extension.pyx", line 492, in tables.hdf5extension.File._g_new
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "H5F.c", line 511, in H5Fopen
    unable to open file
  File "H5Fint.c", line 1519, in H5F_open
    unable to lock the file
  File "H5FD.c", line 1650, in H5FD_lock
    driver lock request failed
  File "H5FDsec2.c", line 941, in H5FD_sec2_lock
    unable to lock file, errno = 11, error message = 'Resource temporarily unavailable'

End of HDF5 error back trace

Unable to open/create file '/research/rgs01/scratch_lsf/lsftmpdir/nodecn257/93666268.tmpdir/tmpat8phv8x/stg0d07df0c-2800-4570-b2b5-578da606b2ff/PBMC12k_reduced.h5'
Traceback (most recent call last):
  File "/research/rgs01/home/clusterHome/lding/.conda/envs/py361_test/lib/python3.6/site-packages/MICA-0.1.0-py3.6.egg/MICA/bin/clustering.py", line 87, in <module>
    main()
  File "/research/rgs01/home/clusterHome/lding/.conda/envs/py361_test/lib/python3.6/site-packages/MICA-0.1.0-py3.6.egg/MICA/bin/clustering.py", line 42, in main
    args.umap_min_dist, args.tsne_perplexity, args.plot_dim, args.n_thread, args.dim_km)
  File "/research/rgs01/home/clusterHome/lding/.conda/envs/py361_test/lib/python3.6/site-packages/MICA-0.1.0-py3.6.egg/MICA/bin/clustering.py", line 69, in clustering
    common_name=out_name, dims=dim_km, num_processes=n_processes)
  File "/research/rgs01/home/clusterHome/lding/.conda/envs/py361_test/lib/python3.6/site-packages/MICA-0.1.0-py3.6.egg/MICA/bin/clustering.py", line 47, in km_multiprocess
    hdf = pd.HDFStore(mi_file)
  File "/home/lding/.conda/envs/py361_test/lib/python3.6/site-packages/pandas/io/pytables.py", line 505, in __init__
    self.open(mode=mode, **kwargs)
  File "/home/lding/.conda/envs/py361_test/lib/python3.6/site-packages/pandas/io/pytables.py", line 627, in open
    self._handle = tables.open_file(self._path, self._mode, **kwargs)
  File "/home/lding/.conda/envs/py361_test/lib/python3.6/site-packages/tables-3.5.2-py3.6-linux-x86_64.egg/tables/file.py", line 320, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "/home/lding/.conda/envs/py361_test/lib/python3.6/site-packages/tables-3.5.2-py3.6-linux-x86_64.egg/tables/file.py", line 784, in __init__
    self._g_new(filename, mode, **params)
  File "tables/hdf5extension.pyx", line 492, in tables.hdf5extension.File._g_new
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "H5F.c", line 511, in H5Fopen
    unable to open file
  File "H5Fint.c", line 1519, in H5F_open
    unable to lock the file
  File "H5FD.c", line 1650, in H5FD_lock
    driver lock request failed
  File "H5FDsec2.c", line 941, in H5FD_sec2_lock
    unable to lock file, errno = 11, error message = 'Resource temporarily unavailable'

End of HDF5 error back trace

Unable to open/create file '/research/rgs01/scratch_lsf/lsftmpdir/nodecn257/93666268.tmpdir/tmpygbj2irf/stgd5725581-afe0-4cf9-8759-1e05501f7ef5/PBMC12k_reduced.h5'
Traceback (most recent call last):
  File "/research/rgs01/home/clusterHome/lding/.conda/envs/py361_test/lib/python3.6/site-packages/MICA-0.1.0-py3.6.egg/MICA/bin/clustering.py", line 87, in <module>
    main()
  File "/research/rgs01/home/clusterHome/lding/.conda/envs/py361_test/lib/python3.6/site-packages/MICA-0.1.0-py3.6.egg/MICA/bin/clustering.py", line 42, in main
    args.umap_min_dist, args.tsne_perplexity, args.plot_dim, args.n_thread, args.dim_km)
  File "/research/rgs01/home/clusterHome/lding/.conda/envs/py361_test/lib/python3.6/site-packages/MICA-0.1.0-py3.6.egg/MICA/bin/clustering.py", line 69, in clustering
    common_name=out_name, dims=dim_km, num_processes=n_processes)
  File "/research/rgs01/home/clusterHome/lding/.conda/envs/py361_test/lib/python3.6/site-packages/MICA-0.1.0-py3.6.egg/MICA/bin/clustering.py", line 47, in km_multiprocess
    hdf = pd.HDFStore(mi_file)
  File "/home/lding/.conda/envs/py361_test/lib/python3.6/site-packages/pandas/io/pytables.py", line 505, in __init__
    self.open(mode=mode, **kwargs)
  File "/home/lding/.conda/envs/py361_test/lib/python3.6/site-packages/pandas/io/pytables.py", line 627, in open
    self._handle = tables.open_file(self._path, self._mode, **kwargs)
  File "/home/lding/.conda/envs/py361_test/lib/python3.6/site-packages/tables-3.5.2-py3.6-linux-x86_64.egg/tables/file.py", line 320, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "/home/lding/.conda/envs/py361_test/lib/python3.6/site-packages/tables-3.5.2-py3.6-linux-x86_64.egg/tables/file.py", line 784, in __init__
    self._g_new(filename, mode, **params)
  File "tables/hdf5extension.pyx", line 492, in tables.hdf5extension.File._g_new
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "H5F.c", line 511, in H5Fopen
    unable to open file
  File "H5Fint.c", line 1519, in H5F_open
    unable to lock the file
  File "H5FD.c", line 1650, in H5FD_lock
    driver lock request failed
  File "H5FDsec2.c", line 941, in H5FD_sec2_lock
    unable to lock file, errno = 11, error message = 'Resource temporarily unavailable'

End of HDF5 error back trace

Unable to open/create file '/research/rgs01/scratch_lsf/lsftmpdir/nodecn257/93666268.tmpdir/tmpx7y22iru/stgbf77246b-014b-44c4-87d1-d50c26f59f3d/PBMC12k_reduced.h5'
Traceback (most recent call last):
  File "/research/rgs01/home/clusterHome/lding/.conda/envs/py361_test/lib/python3.6/site-packages/MICA-0.1.0-py3.6.egg/MICA/bin/clustering.py", line 87, in <module>
    main()
  File "/research/rgs01/home/clusterHome/lding/.conda/envs/py361_test/lib/python3.6/site-packages/MICA-0.1.0-py3.6.egg/MICA/bin/clustering.py", line 42, in main
    args.umap_min_dist, args.tsne_perplexity, args.plot_dim, args.n_thread, args.dim_km)
  File "/research/rgs01/home/clusterHome/lding/.conda/envs/py361_test/lib/python3.6/site-packages/MICA-0.1.0-py3.6.egg/MICA/bin/clustering.py", line 69, in clustering
    common_name=out_name, dims=dim_km, num_processes=n_processes)
  File "/research/rgs01/home/clusterHome/lding/.conda/envs/py361_test/lib/python3.6/site-packages/MICA-0.1.0-py3.6.egg/MICA/bin/clustering.py", line 47, in km_multiprocess
    hdf = pd.HDFStore(mi_file)
  File "/home/lding/.conda/envs/py361_test/lib/python3.6/site-packages/pandas/io/pytables.py", line 505, in __init__
    self.open(mode=mode, **kwargs)
  File "/home/lding/.conda/envs/py361_test/lib/python3.6/site-packages/pandas/io/pytables.py", line 627, in open
    self._handle = tables.open_file(self._path, self._mode, **kwargs)
  File "/home/lding/.conda/envs/py361_test/lib/python3.6/site-packages/tables-3.5.2-py3.6-linux-x86_64.egg/tables/file.py", line 320, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "/home/lding/.conda/envs/py361_test/lib/python3.6/site-packages/tables-3.5.2-py3.6-linux-x86_64.egg/tables/file.py", line 784, in __init__
    self._g_new(filename, mode, **params)
  File "tables/hdf5extension.pyx", line 492, in tables.hdf5extension.File._g_new
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "H5F.c", line 511, in H5Fopen
    unable to open file
  File "H5Fint.c", line 1519, in H5F_open
    unable to lock the file
  File "H5FD.c", line 1650, in H5FD_lock
    driver lock request failed
  File "H5FDsec2.c", line 941, in H5FD_sec2_lock
    unable to lock file, errno = 11, error message = 'Resource temporarily unavailable'

End of HDF5 error back trace

Unable to open/create file '/research/rgs01/scratch_lsf/lsftmpdir/nodecn257/93666268.tmpdir/tmpoepfbbbb/stgdafed1ba-cf6d-4110-96bb-86e62d6f90be/PBMC12k_reduced.h5'
Traceback (most recent call last):
  File "/research/rgs01/home/clusterHome/lding/.conda/envs/py361_test/lib/python3.6/site-packages/MICA-0.1.0-py3.6.egg/MICA/bin/clustering.py", line 87, in <module>
    main()
  File "/research/rgs01/home/clusterHome/lding/.conda/envs/py361_test/lib/python3.6/site-packages/MICA-0.1.0-py3.6.egg/MICA/bin/clustering.py", line 42, in main
    args.umap_min_dist, args.tsne_perplexity, args.plot_dim, args.n_thread, args.dim_km)
  File "/research/rgs01/home/clusterHome/lding/.conda/envs/py361_test/lib/python3.6/site-packages/MICA-0.1.0-py3.6.egg/MICA/bin/clustering.py", line 69, in clustering
    common_name=out_name, dims=dim_km, num_processes=n_processes)
  File "/research/rgs01/home/clusterHome/lding/.conda/envs/py361_test/lib/python3.6/site-packages/MICA-0.1.0-py3.6.egg/MICA/bin/clustering.py", line 47, in km_multiprocess
    hdf = pd.HDFStore(mi_file)
  File "/home/lding/.conda/envs/py361_test/lib/python3.6/site-packages/pandas/io/pytables.py", line 505, in __init__
    self.open(mode=mode, **kwargs)
  File "/home/lding/.conda/envs/py361_test/lib/python3.6/site-packages/pandas/io/pytables.py", line 627, in open
    self._handle = tables.open_file(self._path, self._mode, **kwargs)
  File "/home/lding/.conda/envs/py361_test/lib/python3.6/site-packages/tables-3.5.2-py3.6-linux-x86_64.egg/tables/file.py", line 320, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "/home/lding/.conda/envs/py361_test/lib/python3.6/site-packages/tables-3.5.2-py3.6-linux-x86_64.egg/tables/file.py", line 784, in __init__
    self._g_new(filename, mode, **params)
  File "tables/hdf5extension.pyx", line 492, in tables.hdf5extension.File._g_new
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "H5F.c", line 511, in H5Fopen
    unable to open file
  File "H5Fint.c", line 1519, in H5F_open
    unable to lock the file
  File "H5FD.c", line 1650, in H5FD_lock
    driver lock request failed
  File "H5FDsec2.c", line 941, in H5FD_sec2_lock
    unable to lock file, errno = 11, error message = 'Resource temporarily unavailable'

End of HDF5 error back trace

Unable to open/create file '/research/rgs01/scratch_lsf/lsftmpdir/nodecn257/93666268.tmpdir/tmp33igsuo1/stg721ff009-e8c7-4c7c-8084-13e3d868b7fa/PBMC12k_reduced.h5'
?[1;30mINFO?[0m [job clustering_5] Max memory used: 15MiB
?[1;30mINFO?[0m [job clustering_6] Max memory used: 18MiB
?[1;30mINFO?[0m [job clustering] Max memory used: 17MiB
?[1;30mINFO?[0m [job clustering_3] Max memory used: 19MiB
?[1;30mINFO?[0m [job clustering_7] Max memory used: 18MiB
?[1;30mERROR?[0m ?[31m[job clustering_5] Job error:
Error collecting output for parameter 'out_fig':

**Comment by pNKz7mD0jz89KSShpK04tgEKc6OtEInKODtyxWB** [comment]
?[1;30mWARNING?[0m ?[33mFinal process status is permanentFail?[0m
Traceback (most recent call last):
  File "/home/lding/.conda/envs/py361_test/bin/mica", line 11, in <module>
    load_entry_point('MICA==0.1.0', 'console_scripts', 'mica')()
  File "/home/lding/.conda/envs/py361_test/lib/python3.6/site-packages/MICA-0.1.0-py3.6.egg/MICA/mica.py", line 113, in main
    run_shell_command_call(cmd)
  File "/home/lding/.conda/envs/py361_test/lib/python3.6/site-packages/MICA-0.1.0-py3.6.egg/MICA/mica.py", line 123, in run_shell_command_call
    subprocess.check_call(cmd_to_exec)
  File "/home/lding/.conda/envs/py361_test/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cwltool', '--parallel', '--debug', '--leave-tmpdir', '--outdir', '/research/rgs01/home/clusterHome/lding/test/bluesky/mica_out', '/research/rgs01/home/clusterHome/lding/.conda/envs/py361_test/lib/python3.6/site-packages/MICA-0.1.0-py3.6.egg/MICA/cwl/mica.cwl', '/research/rgs01/home/clusterHome/lding/test/bluesky/mica_out/mica.yml']' returned non-zero exit status 1.

**Comment by pNKz7mD0jz89KSShpK04tgEKc6OtEInKODtyxWB** [comment]
commit "fixing HDF5 file lock error" should fix it
